### ISSUE TITLE
Add Badges to README

### ISSUE THREAD

**Issue by juggler434** [juggler434/marvel_server#12]
# USER STORY
As a developer, ISBAT see a series of badges displayed on the README

# ACCEPTANCE CRITERIA
## GIVEN
A developer

## WHEN
Looking at the repository page

## THEN
they should be able to see a badge for build passing, code coverage, go documentation

**Comment by juggler434** [comment]
Blocked by #4

**Comment by juggler434** [comment]
No Go Docuemntation badge

**Comment by tashachin** [comment]
Excuse me, it looks like you're using Cucumber-style syntax for business development.

Can I clarify if you're using IntelliJ's IDE for your development as well?

**Comment by juggler434** [comment]
Currently using this syntax because it's what my team at work was using for project management, so trying it out.  I personally use GoLand (which is the Go equivalent of IntelliJ).  There isn't anything in the project that requires a specific IDE to run or develop, everything should compile easily into a binary that can be run from any unix style machine.
